version: 2.1
jobs:
  build:
    docker:
      - image: python:3

    steps:
      - checkout
      - run: pip install django>=3.0
      - run: pip install -U pip setuptools tox
      - run: tox --recreate